config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'), # Question 모델 데이터 중 id 값이 2 인 데이터를 조회하라
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'), # form 엘리먼트의 URL 매핑 추가
    path('question/create/', views.question_create, name='question_create'),
]

pybo/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200) # 제목
    content = models.TextField() # 내용
    create_date = models.DateTimeField() # 작성일시

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

pybo/forms.py
from django import forms # 페이지 요청시 전달되는 파라미터들을 쉽게 관리하기 위해 사용하는 클래스. 필수 파라미터가 누락되지않았는지, 파라미터 형태가 적절한지 검증.
                        # HTML 자동생성하거나 폼에 연결된 모델을 이용하여 데이터 저장도 가능함.
from pybo.models import Question, Answer

# 장고의 폼은 일반 폼(forms.Form)과 모델 폼(forms.ModelForm)이 있음. 모델 폼은 모델(Model)과 연결된 폼으로 폼을 저장하면 연결된 모델의 데이터를 저장할 수 있는 폼
# 모델 폼은 이너 클래스인 Meta 클래스가 반드시 필요함. Meta 클래스에는 사용할 모델과 모델의 속성을 정의해야함

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question # 사용할 모델
        fields = ['subject', 'content'] # QuestionForm에서 사용할 Question 모델의 속성

        # widgets = { # Meta 클래스의 widgets 속성을 지정하면 입력 필드에 form-contorl과 같은 부트스트랩 클래스를 추가할 수 있음.
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }

        # 질문등록 화면에서 영어를 한글로 변경
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변 내용'
        }

pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Question
from django.utils import timezone
from .forms import QuestionForm, AnswerForm

# Create your views here.
def index(request):
    '''
    pybo 목록 출력
    '''
    question_list = Question.objects.order_by('-create_date') # order_by: 조회한 데이터를 특정 속성으로 정렬, '-create_date'는 -기호가 앞에 붙어있어 작성일시의 역순을 의미
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context) # context에 있는 Question 모델 데이터 question_list를 'pybo/question_list.html' 파일에 적용하여 html 코드로 반환


def detail(request, question_id):
    '''
    pybo 내용 출력
    '''
    # question = Question.objects.get(id=question_id) # URL 매핑에 있던 question_id: /pybo/2/ 페이지가 호출되면 최종으로 detail 함수의 매개변수 question_id에 2가 전달
    question = get_object_or_404(Question, pk=question_id) # 존재하지 않는 페이지에 접속하면 오류 대신 404 페이지 출력
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


def answer_create(request, question_id): # request: question.html에서 textarea에 입력된 파이썬 객체 // question_id: URL 매핑 정보값
    ''''
    pybo 답변 등록
    '''
    question = get_object_or_404(Question, pk=question_id)
    # question.answer_set.create(content=request.POST.get('content'), # textarea에 입력된 파이썬 객체에 담겨진 값을 추출하기 위한 코드.
    #                                                                 # Question 모델을 통해 Answer 모델 생성을 위해 answer_set.create 활용
    #                            create_date = timezone.now())
    # # request.POST.get('content')는 POST 형식으로 전송된 form 데이터 항목 중 name이 content인 값을 의미
    # # Answer 모델이 Question 모델을 FK로 참조하고 있으므로 question.answer_set같은 표현 사용가능
    #
    # return redirect('pybo:detail', question_id=question.id) # redirect: 함수에 전달된 값을 참고하여 페이지 이동 수행

    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question_id)
    else: # 답변 등록은 POST 방식만 사용되기 때문에 else 구문에서 호출되지 않으나, 패턴의 통일성을 위해 작성
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


def question_create(request):
    '''
    pybo 질문 등록
    '''

    if request.method == 'POST': # 질문 등록 후 저장하기 버튼을 클릭하면 POST 방식으로 요청됨. form 태그에 action 속성이 지정되지 않으면 페이지가 디폴트 action으로 설정됨
                                # 저장하기를 누르면 question_create 함수가 실행되고 request.method 값은 POST가 되어 다음 코드들이 실행됨.
        form = QuestionForm(request.POST)
        if form.is_valid(): # form이 유효한지 검사함.
            question = form.save(commit=False) # form으로 Question 데이터를 저장하기 위한 코드. QuestionForm이 Question 모델과 연결된 폼이기 때문에 이와같이 사용.
                                                # commit=False는 임시저장을 의미. 즉, 실제 데이터에는 아직 데이터베이스에 저장되지 않은 상태.
                                                # 위 옵션을 주지 않으면 create_date에 값이 없다는 오류가 발생함. QuestionForm에는 현재 subject, content 속성만 정의됐고
                                                # create_date 속성은 없기 때문. 이 때문에 임시 저장한 후 question 객체를 리턴 받아 create_date에 값을 설정한 후 question.save()
            question.create_date = timezone.now() # 데이터 저장 시점에 자동 생성해야 하는 값이므로 QuestionForm에 등록하지 않음
            question.save()
            return redirect('pybo:index') # 질문화면 목록으로 이동

    else: # "질문 등록하기" 버튼을 클릭한 경우에는 페이지가 GET 방식으로 요청되어 위 함수가 실행됨. 링크를 통해 페이지를 요청할 때는 무조건 GET 방식이 사용됨

        form = QuestionForm()
    context = {'form': form} # {'form': form}은 템플릿에서 질문 등록시 사용할 폼 엘리먼트를 생성할 때 쓰임

    return render(request, 'pybo/question_form.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>

<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}


        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}


        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
<!--      action을 지정하지 않는 경우 현재 페이지의 URL이 디폴트 action으로 설정됨.-->
<!--      동일한 템플릿을 여러 기능에서 함께 사용할 경우에는 이처럼 form의 action 속성을 비워두는 기법을 종종 사용함.-->

        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
<!--            제목 항목에서 value 값은 오류가 발생했을 경우 기존에 입력했던 값을 유지하기 위함. 장고의 템플릿 필터는 |default_if_none:'' 처럼 | 기호와 함께 사용됨-->


        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
<!--{{ form.as_p }}에서 자동으로 생성되는 HTML 대신 제목과 내용에 해당되는 HTMl코드를 작성함. question_create 함수에서 form.is_valid()가 실패할 경우-->
<!--        발생하는 오류의 내용을 표시하기 위해 오류를 표시하는 영역을 추가함-->



<!--        {{ form.as_p }}-->
<!--      question_create 함수에서 전달한 QuestionForm의 객체. 폼에 정의한 subject, content 속성에 해당하는 HTML 코드를 자동으로 생성-->

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>

{% endblock %}